### ISSUE TITLE
New UI. 

### ISSUE THREAD

**Issue by theREALaltoid** [metamarcdw/nwweb#3]
I already filled out the contribution form on the NoWallet repo here: https://github.com/metamarcdw/nowallet/issues/11
The repo with the changed files is here: https://github.com/theREALaltoid/NWWEB-UI

**Comment by metamarcdw** [comment]
Please check out the documentation here:
https://help.github.com/articles/creating-a-pull-request/

In order to contribute code, you must create a fork and start a proper pull request. Thank you.
